name: Deploy to FGA

on:
  workflow_call:
    inputs:
      WORKOS_ACTIVE_ENVIRONMENT:
        required: true
        type: string
    secrets:
      WORKOS_API_KEY:
        required: true

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      # Install WorkOS CLI and apply schema to WorkOS
      - name: Install WorkOS CLI
        uses: workos/cli-action@v1
        with:
          version: latest
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use the file
        run: cat ./schema.txt
      - name: Apply Schema to WorkOS
        run: |
          echo ${{ secrets.WORKOS_API_KEY }}
          workos fga schema apply ./schema.txt
        env:
          WORKOS_ACTIVE_ENVIRONMENT: headless
          WORKOS_ENVIRONMENTS_HEADLESS_NAME: local
          WORKOS_ENVIRONMENTS_HEADLESS_ENDPOINT: http://localhost:8001
          WORKOS_ENVIRONMENTS_HEADLESS_API_KEY:  ${{ secrets.WORKOS_API_KEY }}
          WORKOS_ENVIRONMENTS_HEADLESS_TYPE: Sandbox
